### ISSUE TITLE
代码MyModel类的问题

### ISSUE THREAD

**Issue by SkyJoyTianle** [Zodiark-ch/masters-of-our-EMNLP2023-papers#1]
class MyModel(nn.Module):
    
    def __init__(self, args, num_class):
        super(MyModel,self).__init__()
        self.args=args
        #self.bert=RobertaModel.from_pretrained(self.args.roberta_pretrain_path)
        if self.args.withvae==False:
      
        self.vae=CAVAE_dagnn(args)
        self.pred1=Pre_Predictions(args,num_class)
        self.pred2=Pre_Predictions(args,num_class)
 您好，请问if后面是不是少了一行代码

**Comment by Zodiark-ch** [comment]
Hi，if==False的情况是测试用的gnn，后来用作加ablation model了，所以最终上传的时候删掉了，代码一直跑if==true即可。
