### ISSUE TITLE
Code not corresponding to the paper.

### ISSUE THREAD

**Issue by luisivanhr** [Zodiark-ch/masters-of-our-EMNLP2023-papers#2]
Sorry, but the provided code does not contain at all the model described in the paper How to Enhance Causal Discrimination of Utterances: A Case on Affective Reasoning.

The run.py files are used to run a Variational Autoencoder model, not the GAT Autoencoder proposed in this paper. Could you please indicate how to run the code for said paper?

Thank you

**Comment by Zodiark-ch** [comment]
Hi, there must be some misunderstandings, e.g., ablation/dagvae.py corresponds to the Skt VI in the paper.

**Comment by luisivanhr** [comment]
Why is information like this not commented on the code?

**Comment by Zodiark-ch** [comment]
I‘m sorry to introduce disturbance, but this paper is a long-term reviewing process (at least 4-5 reviews and revisions). Hence there are probably some new notions emerging in the later revisions that I didn't modify in the code (because only the naming changes but functions are still). So it could make the code more difficult to understand.

**Comment by luisivanhr** [comment]
I see, thank you for the information.
Could you point out which is the model to call for the ECPE and ERC tasks for the method described in
How to Enhance Causal Discrimination of Utterances: A Case on Affective Reasoning?

**Comment by luisivanhr** [comment]
> Hi, there must be some misunderstandings, e.g., ablation/dagvae.py corresponds to the Skt VI in the paper.

Also, I am sorry to emphasize on this point, but ablation/dagvae.py does not correspond to Skeleton VI since it does not contain any part of the GAT network proposed in the paper.

**Comment by luisivanhr** [comment]
Also, I am afraid that your Equation (5) for the Graph attention is wrong, since the Transpose operation makes no sense here. Also, I cannot find the eLU operation after a Graph Attention layer anywhere in your code. The reason I am being so insistent is because I will benchmark your model with mine. If the code you provide does not reflect the contents of the paper I will be forced to write a code myself with the only hints that you give in the paper. If there are additional considerations to what you do in the paper, then the performance of your method will look lower than it could potentially be.

**Comment by Zodiark-ch** [comment]
Hi， sorry for replying late but I'm busy with my other work. 
I'll answer you in brief. 
You can refer to the table 3 in our papers. I recommend VI (DAG-ERC†+Ours), which is the model in the https://github.com/Zodiark-ch/masters-of-our-EMNLP2023-papers/blob/main/DAG-ECPE/ablation/dagvae.py

and dagvae.py is composed of an encoder and decoder, you can find the  "gats += [GAT_encoder(args.gnn_hidden_dim)]" in the encoder and "gats += [GNN_decoder(args.gnn_hidden_dim)]" in the decoder. 

As for the Equation (5) and *LU activation, maybe they could not match the implementation. I didn't check it, but you can believe the GAT_encoder in gnn_utils.py surely. I'm sure this model can behave around 76 in F1 as the paper shows. 

Good luck!

**Comment by Zodiark-ch** [comment]
The GATencoderlayer in gnn_utils.py corresponds to the Transpose operation and eLU (GAT has robust performance and is the basic model of II IV and V, these 3 skeletons only differ in changing the adj matrix, you can see Figure 5 for details).  You can run gatvae.py to observe its performance. Dagvae.py was indeed coded with some differences. I'm sorry for that. However, it does not matter, the key contribution of these models is using inverse matrix to reflect causal relationships. E.g., b_inv= torch.linalg.solve(I, (I-adjB_list[l+1])) in DAGdecoder and b_inv,_ = torch.solve(I,IB) in GATdecoderlayer.

**Comment by Zodiark-ch** [comment]
You can check these by yourself. I'm sorry for any trouble.

**Comment by luisivanhr** [comment]
Thank you very much for your reply. I will take these (in particular Skeleton VI) for our benchmarks. Looking forward to your next work.
